/**
 * Cross-context message protocol — `docs/ARCHITECTURE.md` §7.2. All of it travels over
 * the runtime messaging channel (via `BrowserAdapter.messaging`).
 *
 * The union below is the target shape. Stage 0-3 shipped only the channel probe; stage
 * 1-1 lands the rest now that the payload types exist (§5.5, §5.1/§5.2, §8.1).
 * Appending message kinds is allowed; changing the meaning of existing fields goes
 * through the doc change protocol.
 *
 * Types only. DSL types come in through `import type` (erased at compile time).
 */
import type { ToolCategory, LlmStep, ToolDefinition } from '@juxbly/dsl'
import type {
  ChatMessage,
  HealthEvaluation,
  PageAnalysis,
  RunError,
} from './runtime'
import type {
  HealthStatus,
  OnboardingFlags,
  RunState,
  RunSummary,
  Settings,
  ToolHealth,
  ToolVersionSummary,
} from './tool-record'

/** Shown in the panel for every real llm call (BYOK transparency). */
export interface TokenUsage {
  prompt_tokens: number
  completion_tokens: number
}

export type ExtensionMessage =
  // Build (panel → background)
  | {
      kind: 'build:propose'
      requestId: string
      conversation: ChatMessage[]
      pageAnalysis: PageAnalysis
      /**
       * A4 level ①: true on the single conservative retry, asking the model for the
       * plainest, most literal reading of the page instead of a clever one.
       */
      conservative?: boolean
      /**
       * The clarification cap reaching the prompt: the model must answer with a draft
       * instead of another question. The cap is enforced in the panel as well — a prompt
       * is a request, the cap is a rule (§9.1).
       */
      noMoreQuestions?: boolean
      /**
       * A3 visual fallback: screenshot attached only after the DOM route
       * failed (base64 PNG). First builds never carry one — a screenshot means page
       * pixels leave this machine for the user's own endpoint, so it must be an
       * explicit, failure-triggered remediation, never the default path.
       */
      screenshot?: string
    }
  | {
      kind: 'build:propose_result'
      requestId: string
      ok: boolean
      reply?: ChatMessage
      tool?: ToolDefinition
      /**
       * What the call cost. BYOK transparency (UI_SPEC §9 rule 4): every real model call
       * is paid for by the user, so the panel shows it even when the answer is a question.
       */
      usage?: TokenUsage
      /**
       * A2 candidates: the model may return several; the content script
       * scores them locally (§5.6) and presents the best. Absent → fall back to `tool`;
       * old behaviour unchanged, backward compatible.
       */
      candidates?: ToolDefinition[]
      error?: string
    }
  /**
   * `tool` is the confirmed definition. `repair` (stage 1-12) marks the write as **a new
   * version of an existing tool** instead of a first save: the background then derives
   * `version + 1`, keeps every old version, and marks the replaced one `ever_broken`
   * (§8.1 / §9.3).
   *
   * It is explicit rather than inferred from "a record with this id already exists": tool
   * ids are generated by a model, and an id collision would otherwise silently turn a new
   * tool into a version of someone else's history.
   */
  | {
      kind: 'build:save_tool'
      tool: ToolDefinition
      repair?: RepairSaveRequest
    }
  /**
   * The reply to `build:save_tool`. Storage is the background's to write (§7.1), so the
   * content script has to be told whether it worked — a save that silently failed would
   * leave the user with a tool they believe they have.
   *
   * `version` (stage 1-12) echoes the version that is now in effect, so a repair can
   * report "v2 is live" instead of a bare yes.
   */
  | { kind: 'build:save_tool_result'; ok: boolean; version?: number; error?: string }
  // Run (content script ↔ background)
  | { kind: 'run:query_tools'; url: string }
  | { kind: 'run:query_tools_result'; tools: ToolDefinition[] }
  | { kind: 'run:llm'; requestId: string; step: LlmStep; input: unknown }
  | {
      kind: 'run:llm_result'
      requestId: string
      ok: boolean
      output?: unknown
      usage?: TokenUsage
      error?: string
    }
  /**
   * The run layer's closing message (stage 1-10). `summary` feeds Tool Health, `runState`
   * is what the next run starts from (§8.1: the llm cache decision lives in the record,
   * and only the content script has executed the steps that produced it), and `ok` is
   * what separates "the tool worked" from "the tool ran and failed" — the two cases
   * differ in what the background is allowed to conclude from them.
   *
   * Stage 1-11 adds the health inputs, all **optional** so a 1-10-era sender stays valid:
   * `error` is the run engine's failure (the execution layer reads its extract codes),
   * `extract` carries the structure statistics health fingerprints (statistics only —
   * never the records), and `sample` is at most a few records for the semantic layer.
   * The sample is page data crossing to the background, where the key lives anyway (§7.1);
   * it is wrapped as a data section by the prompt builder and never stored, never logged.
   */
  | {
      kind: 'run:report'
      toolId: string
      summary: RunSummary
      ok?: boolean
      runState?: RunState
      error?: RunError
      extract?: { hitCount: number; fieldPresence: Record<string, number> }
      sample?: unknown[]
    }
  /**
   * The reply to `run:report` (stage 1-11): the freshly stored health plus the four-layer
   * verdict, so the panel can render the badge immediately instead of re-reading storage.
   * `ok` is false when the tool was deleted mid-flight — nothing was written.
   */
  | {
      kind: 'run:report_result'
      toolId: string
      ok: boolean
      health?: ToolHealth
      evaluation?: Pick<HealthEvaluation, 'status' | 'changed' | 'reason' | 'layers'>
    }
  /**
   * The mirror of `run:report`: a run starts by asking what the previous one left behind.
   * Without it the content script would rebuild the run state from scratch on every page
   * load, and an unchanged page would pay for the same model call again and again.
   */
  | { kind: 'run:load_state'; toolId: string }
  | { kind: 'run:load_state_result'; toolId: string; runState: RunState | null }
  /**
   * "Don't keep" on the retention line (UI_SPEC §7.3) — the first writer of the delete
   * path. Stage 1-13 reuses it from the management surface.
   */
  | { kind: 'tool:delete'; toolId: string }
  | { kind: 'tool:delete_result'; ok: boolean; toolId: string; error?: string }
  /**
   * Rollback (stage 1-12, §9.3 / C3): make an older version the effective one again.
   *
   * It is **not** a save. No definition is produced and none is validated against the
   * page — the version was validated when it was written. What it changes is which
   * definition is in effect, which is why it carries no `tool` payload at all: sending
   * one would let a caller roll back *and* silently rewrite history in the same act.
   *
   * `tool:rollback_result` echoes the version now in effect; `error` is `TOOL_NOT_FOUND`,
   * `VERSION_NOT_FOUND` or `SAVE_FAILED`.
   */
  | { kind: 'tool:rollback'; toolId: string; version: number }
  | { kind: 'tool:rollback_result'; ok: boolean; version?: number; error?: string }
  /**
   * Stage 1-16: the version history behind the rollback list (§8.1 / C3).
   *
   * `run:query_tools` answers definitions only, and `versions[]` lives on the record — so
   * no panel could show that a rollback is even possible, which is the gap that left
   * 1-12's list unwired (§4: `VersionList` existed, nothing reachable imported it). This
   * read is the wiring: a tool id in, the history out.
   *
   * Deliberately narrow — `versions` and the version in effect, and nothing else. No
   * health, no usage, no settings: a wider "give me the record" message is how a page
   * context ends up holding data it has no use for.
   */
  | { kind: 'tool:get'; toolId: string }
  | {
      kind: 'tool:get_result'
      /** The version currently in effect — the one the list marks, not a target. */
      version: number
      versions: ToolVersionSummary[]
    }
  /**
   * The four one-shot milestones (§8.1). The content script cannot read storage, and the
   * run panel needs `first_tool_built` to choose the promise line — so the flags are
   * asked for, exactly like settings. No secret travels in either direction.
   */
  | { kind: 'onboarding:get' }
  | { kind: 'onboarding:get_result'; flags: OnboardingFlags | null }
  /**
   * Stage 1-13: set one milestone. The four flags are **independent one-shot facts, not a
   * progress bar** — any node may fire first, so a caller sets its own bit only and the
   * background merges (a flag already `true` stays `true`: whether the user was shown
   * something is a fact about the past).
   *
   * The reply echoes the merged flags so the caller renders from the same source it will
   * read next time rather than from its own patch.
   */
  | { kind: 'onboarding:set'; patch: Partial<OnboardingFlags> }
  | { kind: 'onboarding:set_result'; flags: OnboardingFlags }
  /**
   * Stage 1-13: the toolbar overview's rows. `run:query_tools` answers definitions only,
   * and the overview also needs usage and health, which live on the record.
   *
   * `domain` is a host and never a URL (UI_SPEC §7.2); `lastUsedAt` is the more recent of
   * `last_run_at` / `last_export_at` (§8.1: exporting without running is a use too).
   */
  | { kind: 'tool:list' }
  | { kind: 'tool:list_result'; tools: ToolOverviewItem[] }
  /**
   * Stage 1-13: focus the tab already showing this tool's page, or open one when there is
   * none (UI_SPEC §7.2). The popup hands over a URL and nothing else — choosing a tab is
   * a platform action, reserved to the assembly layer (§6.4.1).
   */
  | { kind: 'tab:open'; url: string }
  | { kind: 'tab:open_result'; ok: boolean; error?: string }
  // Health (content script → background; the semantic check calls the model, key stays in background)
  | { kind: 'health:semantic_check'; requestId: string; fields: string[]; sample: unknown[] }
  | {
      kind: 'health:semantic_check_result'
      requestId: string
      ok: boolean
      verdict?: 'ok' | 'suspicious'
      reason?: string
      usage?: TokenUsage
      /**
       * Present only when `ok` is false: the same category codes as `run:llm_result`
       * (§5.5), because "no key yet" and "the endpoint is down" are different next
       * actions for the user, and a failed check must read as "no answer" — never as
       * a fabricated verdict (§10: no network is not a broken tool).
       */
      error?: string
    }
  // Export (content script → background)
  | { kind: 'export:download_csv'; filename: string; csv: string }
  | { kind: 'export:download_json'; filename: string; json: string }
  /**
   * The reply to a download request (stage 1-15). A download can be refused — by a
   * permission gap, quota or an intercepting browser — and the panel must surface that and
   * offer a retry, never pretend a refused download was delivered.
   */
  | { kind: 'export:download_result'; ok: boolean; error?: string }
  /**
   * A successful export (copy, csv or json) records usage. Storage is the background's to
   * write (§7.1), and the strict §7.2 download messages carry no tool id, so the three
   * formats share this one bookkeeping hop after they deliver (stage 1-15).
   */
  | { kind: 'export:record_usage'; toolId: string }
  // Settings (popup / options ↔ background)
  | { kind: 'settings:get' }
  | {
      kind: 'settings:get_result'
      /**
       * The public subset only. The BYOK key never crosses back to a content script, so
       * the reply is a flat allowlist, not a `Settings` object (stage 1-8; §12).
       */
      floating_ball_enabled: boolean
      /**
       * Stage 1-13: a boolean *about* the key, not the key. The build panel needs it to
       * decide whether onboarding node ③ must ask before the first model call, and
       * "is one configured" is not a secret.
       */
      key_set: boolean
    }
  | { kind: 'settings:set'; patch: Partial<Settings> }
  /**
   * Storage is the last gate before a half-written configuration is kept — the same
   * reason `build:save_tool` answers (§9.1). A silent failure here leaves the user
   * believing their key was saved while the next call reports "not configured".
   */
  | { kind: 'settings:set_result'; ok: boolean; error?: string }
  /**
   * The options page's own read (stage 1-13). Separate from `settings:get` on purpose:
   * that one is answered to content scripts, so every field added to it would become
   * readable from the page context. This one is answered to the extension's own options
   * page and carries the endpoint and the model back, plus `key_hint` — a masked tail
   * (`…1234`) computed inside `packages/llm`, the only reader of the key field (§12.2).
   * The key's value never appears in a message in either direction.
   */
  | { kind: 'settings:manage' }
  | {
      kind: 'settings:manage_result'
      key_set: boolean
      key_hint: string | null
      api_base_url: string | null
      model: string | null
      floating_ball_enabled: boolean
    }
  /**
   * Stage 1-13: one minimal call against a **candidate** configuration, before it is
   * saved ("test connection").
   *
   * The candidate is a `Partial<Settings>` rather than three loose fields so the key
   * travels under the same declared type as `settings:set` — one shape, one path, and no
   * second spelling of the credential field anywhere in the tree. It is answered only to
   * the extension's own options page.
   *
   * The key never comes back: the reply carries `ok` and, on failure, an `LlmErrorCode`
   * as `error`.
   */
  | { kind: 'llm:connectivity'; settings: Partial<Settings> }
  | { kind: 'llm:connectivity_result'; ok: boolean; error?: string }
  /**
   * Stage 1-13: the management page's three numbers (§7.2 / §7.4). Computed in the
   * background from the stored records, so the sum and the list can never be read from
   * two different snapshots of the same storage.
   */
  | { kind: 'stats:get' }
  | { kind: 'stats:get_result'; stats: UsageStats }
  // Internal: channel probe, NOT business protocol.
  // The `internal:` prefix keeps it out of the business namespaces so a later stage
  // cannot mistake it for a real protocol message.
  | { kind: 'internal:ping' }
  | { kind: 'internal:pong'; ok: true }
  // Internal: background → content command forwarding. `commands.onCommand` only fires
  // in the service worker, so the shortcut is relayed to the active tab (stage 1-8).
  | { kind: 'internal:command'; command: string }

export type InternalPing = Extract<ExtensionMessage, { kind: 'internal:ping' }>
export type InternalPong = Extract<ExtensionMessage, { kind: 'internal:pong' }>

/**
 * What a repair carries across the boundary (stage 1-12).
 *
 * `trigger` is the only thing that decides whether the replaced version is marked
 * `ever_broken`: a breakage is evidence, an edit is not. `note` is the reason shown next
 * to the version in the rollback list — it is copy, so it is composed by the caller from
 * `packages/ui/src/copy` and never invented here.
 */
export interface RepairSaveRequest {
  toolId: string
  trigger: 'broken' | 'user'
  note: string
}

/**
 * One row of the toolbar overview (stage 1-13; `UI_SPEC` §7.2).
 *
 * Deliberately **not** a `ToolRecord`: the popup needs six display facts, and handing it
 * a record would push the full definition, the run state and every version into a surface
 * whose only job is "find the tool again".
 */
export interface ToolOverviewItem {
  toolId: string
  name: string
  category: ToolCategory
  /** Host only — never a full URL (UI_SPEC §7.2). */
  domain: string
  /** The more recent of `last_run_at` / `last_export_at`; null means never used (§8.1). */
  lastUsedAt: string | null
  status: HealthStatus
  /** What a click opens: the site root derived from `url_pattern` (§5.3). */
  url: string
}

/**
 * The options page's view of the BYOK settings — mirrors `settings:manage_result` (§7.2).
 *
 * Declared here, next to the message it mirrors, rather than in `packages/llm`: it is a
 * message shape, and the only reason the llm package produces one is that it is the sole
 * reader allowed to compute `key_hint`. Keeping the *shape* in core is what lets the
 * options page consume it without depending on the package that reads the key.
 */
export interface SettingsView {
  key_set: boolean
  key_hint: string | null
  api_base_url: string | null
  model: string | null
  floating_ball_enabled: boolean
}

/**
 * The management page's three numbers (stage 1-13, UI_SPEC §7.2 / §7.4).
 *
 * `totalRuns` is the sum of `ToolUsage.run_count` and nothing else — the result area
 * counts the same runs, and a second counter would eventually disagree with it. There is
 * deliberately no "time saved": counting runs is countable, estimating saved time needs
 * invented assumptions, which §9 forbids.
 */
export interface UsageStats {
  totalTools: number
  addedThisWeek: number
  totalRuns: number
}

/** The llm step's cross-context hop: the content script has no key, so it asks (§7.1). */
export type RunLlmMessage = Extract<ExtensionMessage, { kind: 'run:llm' }>
export type RunLlmResultMessage = Extract<ExtensionMessage, { kind: 'run:llm_result' }>

/** The run layer's messages (stage 1-10, §7.2). */
export type RunQueryToolsMessage = Extract<ExtensionMessage, { kind: 'run:query_tools' }>
export type RunQueryToolsResultMessage = Extract<ExtensionMessage, {
  kind: 'run:query_tools_result'
}>
export type RunReportMessage = Extract<ExtensionMessage, { kind: 'run:report' }>
export type RunReportResultMessage = Extract<ExtensionMessage, { kind: 'run:report_result' }>
export type RunLoadStateMessage = Extract<ExtensionMessage, { kind: 'run:load_state' }>
export type RunLoadStateResultMessage = Extract<ExtensionMessage, { kind: 'run:load_state_result' }>
export type ToolDeleteMessage = Extract<ExtensionMessage, { kind: 'tool:delete' }>
export type ToolDeleteResultMessage = Extract<ExtensionMessage, { kind: 'tool:delete_result' }>
export type ToolRollbackMessage = Extract<ExtensionMessage, { kind: 'tool:rollback' }>
export type ToolGetMessage = Extract<ExtensionMessage, { kind: 'tool:get' }>
export type ToolGetResultMessage = Extract<ExtensionMessage, { kind: 'tool:get_result' }>
export type ToolRollbackResultMessage = Extract<
  ExtensionMessage,
  { kind: 'tool:rollback_result' }
>
export type ExportDownloadCsvMessage = Extract<ExtensionMessage, { kind: 'export:download_csv' }>
export type ExportDownloadJsonMessage = Extract<ExtensionMessage, { kind: 'export:download_json' }>
export type ExportDownloadResultMessage = Extract<ExtensionMessage, {
  kind: 'export:download_result'
}>
export type ExportRecordUsageMessage = Extract<ExtensionMessage, { kind: 'export:record_usage' }>
export type OnboardingGetResultMessage = Extract<ExtensionMessage, {
  kind: 'onboarding:get_result'
}>
export type OnboardingSetMessage = Extract<ExtensionMessage, { kind: 'onboarding:set' }>
export type OnboardingSetResultMessage = Extract<ExtensionMessage, {
  kind: 'onboarding:set_result'
}>
export type ToolListResultMessage = Extract<ExtensionMessage, { kind: 'tool:list_result' }>
export type TabOpenMessage = Extract<ExtensionMessage, { kind: 'tab:open' }>
export type TabOpenResultMessage = Extract<ExtensionMessage, { kind: 'tab:open_result' }>
export type SettingsGetResultMessage = Extract<ExtensionMessage, { kind: 'settings:get_result' }>
export type SettingsSetMessage = Extract<ExtensionMessage, { kind: 'settings:set' }>
export type SettingsSetResultMessage = Extract<ExtensionMessage, { kind: 'settings:set_result' }>
export type SettingsManageResultMessage = Extract<ExtensionMessage, {
  kind: 'settings:manage_result'
}>
export type LlmConnectivityMessage = Extract<ExtensionMessage, { kind: 'llm:connectivity' }>
export type LlmConnectivityResultMessage = Extract<ExtensionMessage, {
  kind: 'llm:connectivity_result'
}>
export type StatsGetResultMessage = Extract<ExtensionMessage, { kind: 'stats:get_result' }>
export type HealthSemanticCheckMessage = Extract<ExtensionMessage, {
  kind: 'health:semantic_check'
}>
export type HealthSemanticCheckResultMessage = Extract<ExtensionMessage, {
  kind: 'health:semantic_check_result'
}>

export type BuildProposeMessage = Extract<ExtensionMessage, { kind: 'build:propose' }>
export type BuildProposeResultMessage = Extract<ExtensionMessage, { kind: 'build:propose_result' }>
export type BuildSaveToolMessage = Extract<ExtensionMessage, { kind: 'build:save_tool' }>
export type BuildSaveToolResultMessage = Extract<ExtensionMessage, { kind: 'build:save_tool_result' }>

/**
 * Messages cross a trust boundary: anything that arrives over the runtime message
 * channel is `unknown` until proven otherwise.
 */
function hasKind(message: unknown, kind: ExtensionMessage['kind']): boolean {
  return (
    typeof message === 'object' && message !== null && (message as { kind?: unknown }).kind === kind
  )
}

export function isPing(message: unknown): message is InternalPing {
  return hasKind(message, 'internal:ping')
}

export function isPong(message: unknown): message is InternalPong {
  return hasKind(message, 'internal:pong')
}

export function isRunLlm(message: unknown): message is RunLlmMessage {
  return hasKind(message, 'run:llm')
}

/** The run layer's three panel → background messages (§7.2). */
export function isRunQueryTools(message: unknown): message is RunQueryToolsMessage {
  return hasKind(message, 'run:query_tools')
}

export function isRunReport(message: unknown): message is RunReportMessage {
  return hasKind(message, 'run:report')
}

export function isRunLoadState(message: unknown): message is RunLoadStateMessage {
  return hasKind(message, 'run:load_state')
}

export function isToolDelete(message: unknown): message is ToolDeleteMessage {
  return hasKind(message, 'tool:delete')
}

export function isToolRollback(
  message: unknown,
): message is ToolRollbackMessage & { toolId: string; version: number } {
  const candidate = message as { toolId?: unknown; version?: unknown } | null
  return (
    hasKind(message, 'tool:rollback') &&
    typeof candidate?.toolId === 'string' &&
    typeof candidate?.version === 'number'
  )
}

/** The version history read (stage 1-16); `toolId` is the only field worth checking. */
export function isToolGet(message: unknown): message is ToolGetMessage & { toolId: string } {
  return hasKind(message, 'tool:get') && typeof (message as { toolId?: unknown }).toolId === 'string'
}

export function isExportDownloadCsv(message: unknown): message is ExportDownloadCsvMessage {
  return hasKind(message, 'export:download_csv')
}

export function isExportDownloadJson(message: unknown): message is ExportDownloadJsonMessage {
  return hasKind(message, 'export:download_json')
}

/** `toolId` is the only non-kind field; check it as well, like the download messages. */
export function isExportRecordUsage(
  message: unknown,
): message is ExportRecordUsageMessage & { kind: 'export:record_usage'; toolId: string } {
  return hasKind(message, 'export:record_usage') && typeof (message as { toolId?: unknown }).toolId === 'string'
}

/** The build flow's two panel → background messages (§7.2). */
export function isBuildPropose(message: unknown): message is BuildProposeMessage {
  return hasKind(message, 'build:propose')
}

export function isBuildSaveTool(message: unknown): message is BuildSaveToolMessage {
  return hasKind(message, 'build:save_tool')
}

/**
 * Settings writes are a patch, so the only thing worth checking beyond `kind` is that a
 * patch arrived at all: an empty object is a no-op, not an error, and the storage layer
 * merges it.
 */
export function isSettingsSet(message: unknown): message is SettingsSetMessage & {
  patch: Record<string, unknown>
} {
  if (!hasKind(message, 'settings:set')) return false
  const patch = (message as { patch?: unknown }).patch
  return typeof patch === 'object' && patch !== null
}

/** The options page's read; nothing to check but the kind (§7.2). */
export function isSettingsManage(message: unknown): boolean {
  return hasKind(message, 'settings:manage')
}

/**
 * The connectivity test (stage 1-13). The candidate is user input crossing into the
 * background, so it is checked as an object — the same discipline as `settings:set`, and
 * the values themselves are narrowed by `sanitizeSettingsPatch` downstream.
 */
export function isLlmConnectivity(
  message: unknown,
): message is LlmConnectivityMessage & { settings: Record<string, unknown> } {
  if (!hasKind(message, 'llm:connectivity')) return false
  const candidate = (message as { settings?: unknown }).settings
  return typeof candidate === 'object' && candidate !== null
}

/** The stats read; the request is empty, the reply carries the three numbers. */
export function isStatsGet(message: unknown): boolean {
  return hasKind(message, 'stats:get')
}

/** One milestone, set by the node that owns it and by nobody else (stage 1-13). */
export function isOnboardingSet(message: unknown): message is OnboardingSetMessage & {
  patch: Record<string, unknown>
} {
  if (!hasKind(message, 'onboarding:set')) return false
  const patch = (message as { patch?: unknown }).patch
  return typeof patch === 'object' && patch !== null
}

/** The overview list; the reply carries the rows, so the request is empty. */
export function isToolList(message: unknown): boolean {
  return hasKind(message, 'tool:list')
}

/**
 * `tab:open` carries a URL straight into a platform call, so it is checked as a URL and
 * not merely as a string: `javascript:` and `data:` are not pages, and the assembly layer
 * is the last place that could say no.
 */
export function isTabOpen(message: unknown): message is TabOpenMessage & { url: string } {
  if (!hasKind(message, 'tab:open')) return false
  const url = (message as { url?: unknown }).url
  if (typeof url !== 'string') return false
  try {
    const parsed = new URL(url)
    return parsed.protocol === 'https:' || parsed.protocol === 'http:'
  } catch {
    return false
  }
}

/**
 * The semantic health check (stage 1-11). The payload is page data crossing a trust
 * boundary, so the arrays are checked as arrays here and their elements are narrowed
 * again by the handler — `sample` is `unknown[]` on purpose: records are whatever the
 * extract step produced, and no shape is trusted before the prompt wraps them as data.
 */
export function isHealthSemanticCheck(
  message: unknown,
): message is HealthSemanticCheckMessage & {
  requestId: string
  fields: string[]
  sample: unknown[]
} {
  if (!hasKind(message, 'health:semantic_check')) return false
  const m = message as { requestId?: unknown; fields?: unknown; sample?: unknown }
  return (
    typeof m.requestId === 'string' &&
    Array.isArray(m.fields) &&
    m.fields.every((f) => typeof f === 'string') &&
    Array.isArray(m.sample)
  )
}
